files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
options:
  formatter: 'stylish'
  merge-default-rules: false
rules:
  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0

  # Disallows
  no-duplicate-properties:
    - 1
    - exclude:
      - 'white-space'
      - 'font-size'
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1

  # Name Formats
  class-name-format: 1
  variable-name-format: 1

  # Style Guide
  attribute-quotes: 1
  indentation:
    - 1
    - size: 4

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 0